
export const initialState = [{enCours : false, reponse :''},
    {id:null,pseudo:'', score:0, role:'', voted:false}
];

export const mots = [
    {"civil": "chat", "as": "chien", fait:false},
    {"civil": "grain de beauté", "as": "taches de rousseur", fait:false},
    {"civil": "pomme", "as": "poire", fait:false},
    {"civil": "voiture", "as": "quad", fait:false},
    {"civil": "bouteille", "as": "verre", fait:false},
    {"civil": "chaussure", "as": "botte", fait:false},
    {"civil": "melon", "as": "pasteque", fait:false},
    {"civil": "chapeau", "as": "casquette", fait:false},
    {"civil": "magicien", "as": "clown", fait:false},
    {"civil": "lunettes", "as": "monocle", fait:false},
    {"civil": "fleur", "as": "plante", fait:false},
    {"civil": "montagne", "as": "colline", fait:false},
    {"civil": "oiseau", "as": "poisson", fait:false},
    {"civil": "livre", "as": "journal", fait:false},
    {"civil": "lune", "as": "étoile", fait:false},
    {"civil": "guitare", "as": "violon", fait:false},
    {"civil": "café", "as": "thé", fait:false},
    {"civil": "arbre", "as": "buisson", fait:false},
    {"civil": "maison", "as": "cabane", fait:false},
    {"civil": "cheminée", "as": "poêle", fait:false},
    {"civil": "soleil", "as": "lune", fait:false},
    {"civil": "ordinateur", "as": "tablette", fait:false},
    {"civil": "téléphone", "as": "talkie-walkie", fait:false},
    {"civil": "avion", "as": "hélicoptère", fait:false},
    {"civil": "champ", "as": "jardin", fait:false},
    {"civil": "couteau", "as": "fourchette", fait:false},
    {"civil": "musique", "as": "danse", fait:false},
    {"civil": "peinture", "as": "sculpture", fait:false},
    {"civil": "mer", "as": "rivière", fait:false},
    {"civil": "plage", "as": "lac", fait:false},
    {"civil": "étoile", "as": "planète", fait:false},
    {"civil": "étoile filante", "as": "comète", fait:false},
    {"civil": "rire", "as": "sourire", fait:false},
    {"civil": "cri", "as": "chuchotement", fait:false},
    {"civil": "bonheur", "as": "joie", fait:false},
    {"civil": "tristesse", "as": "mélancolie", fait:false},
    {"civil": "pluie", "as": "neige", fait:false},
    {"civil": "vent", "as": "brise", fait:false},
    {"civil": "nuage", "as": "ciel", fait:false},
    {"civil": "arc-en-ciel", "as": "aurore boréale", fait:false},
    {"civil": "tempête", "as": "ouragan", fait:false},
    {"civil": "éclair", "as": "tonnerre", fait:false},
    {"civil": "canard", "as": "cygne", fait:false},
    {"civil": "lion", "as": "tigre", fait:false},
    {"civil": "éléphant", "as": "girafe", fait:false},
    {"civil": "tortue", "as": "escargot", fait:false},
    {"civil": "grenouille", "as": "crapaud", fait:false},
    {"civil": "renard", "as": "loup", fait:false},
    {"civil": "dragon", "as": "licorne", fait:false},
    {"civil": "kangourou", "as": "koala", fait:false},
    {"civil": "perroquet", "as": "colibri", fait:false},
    {"civil": "singe", "as": "chimpanzé", fait:false},
    {"civil": "panda", "as": "raton laveur", fait:false},
    {"civil": "zèbre", "as": "cheval", fait:false},
    {"civil": "chien", "as": "chat", fait:false},
    {"civil": "cheval", "as": "lapin", fait:false},
    {"civil": "lapin", "as": "souris", fait:false},
    {"civil": "souris", "as": "éléphant", fait:false},
    {"civil": "éléphant", "as": "girafe", fait:false},
    {"civil": "girafe", "as": "kangourou", fait:false},
    {"civil": "kangourou", "as": "koala", fait:false},
    {"civil": "koala", "as": "panda", fait:false},
    {"civil": "panda", "as": "pingouin", fait:false},
    {"civil": "pingouin", "as": "perroquet", fait:false},
    {"civil": "perroquet", "as": "serpent", fait:false},
    {"civil": "serpent", "as": "grenouille", fait:false},
    {"civil": "grenouille", "as": "chien", fait:false},
    {"civil": "dauphin", "as": "requin", fait:false},
    {"civil": "requin", "as": "méduse", fait:false},
    {"civil": "méduse", "as": "étoile de mer", fait:false},
    {"civil": "étoile de mer", "as": "poisson", fait:false},
    {"civil": "poisson", "as": "plante", fait:false},
    {"civil": "plante", "as": "arbre", fait:false},
    {"civil": "arbre", "as": "nuage", fait:false},
    {"civil": "nuage", "as": "soleil", fait:false},
    {"civil": "soleil", "as": "lune", fait:false},
    {"civil": "lune", "as": "étoile", fait:false},
    {"civil": "étoile", "as": "planète", fait:false},
    {"civil": "planète", "as": "galaxie", fait:false},
    {"civil": "galaxie", "as": "univers", fait:false},
    {"civil": "univers", "as": "multivers", fait:false},
    {"civil": "multivers", "as": "dimension", fait:false},
    {"civil": "dimension", "as": "réalité", fait:false},
    {"civil": "réalité", "as": "rêve", fait:false},
    {"civil": "rêve", "as": "cauchemar", fait:false},
    {"civil": "cauchemar", "as": "illusion", fait:false},
    {"civil": "illusion", "as": "mirage", fait:false},
    {"civil": "mirage", "as": "oasis", fait:false},
    {"civil": "oasis", "as": "désert", fait:false},
    {"civil": "désert", "as": "plage", fait:false},
    {"civil": "plage", "as": "montagne", fait:false},
    {"civil": "montagne", "as": "vallée", fait:false},
    {"civil": "vallée", "as": "canyon", fait:false},
    {"civil": "canyon", "as": "ravine", fait:false},
    {"civil": "ravine", "as": "ruisseau", fait:false},
    {"civil": "ruisseau", "as": "rivière", fait:false},
    {"civil": "rivière", "as": "lac", fait:false},
    {"civil": "lac", "as": "océan", fait:false},
    {"civil": "océan", "as": "mer"}
];
